ui: tape
browsers:
  - name: chrome
    version: latest
  - name: ie
    version: 9..latest
  - name: microsoftedge
    version: latest
  - name: firefox
    version: 25..latest
  #- name: opera
  #- version: 11..latest
  - name: safari
    version: 6..latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: latest
